server:
  port: 1111

spring:
  cloud:
    gateway:
      routes:
        - id: sample-service
          uri: http://localhost:2222
          predicates:
            - Path=/api/sample/**
          filters:
            - RewritePath=/api/sample/?(?<segment>.*), /$\{segment}
